apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sa
  namespace: dev

---
apiVersion: v1
kind: Pod
metadata:
  name: awscli-test
  namespace: dev
spec:
  serviceAccountName: dev-sa
  restartPolicy: Never
  containers:
  - name: awscli
    image: amazon/aws-cli
    command:
      - aws
      - secretsmanager
      - get-secret-value
      - --secret-id
      - pod-secret
    env:
    - name: AWS_REGION
      value: us-east-1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
