AWSTemplateFormatVersion : "2010-09-09"
Parameters:
  EnvironmentName:
    Type: String
    Default: ""
    Description: Name of the deployment environment
Conditions:
  EnvNameProvided: !Not [!Equals [!Ref EnvironmentName, "" ]]
Resources:
  LambdaPolicy:  # Requires CAPABILITY_IAM or CAPABILITY_NAMED_IAM if using name
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !If [EnvNameProvided,!Sub 'policy-${AWS::StackName}-${EnvironmentName}-${AWS::Region}', !Sub 'policy-${AWS::StackName}-${AWS::Region}']
      Path: /
      Description: Policy to List EC2 instances in aws account
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: logs:CreateLogGroup
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action: 
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-lambda:*"
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !If [EnvNameProvided,!Sub 'role-${AWS::StackName}-${EnvironmentName}-${AWS::Region}', !Sub 'role-${AWS::StackName}-${AWS::Region}']
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
      - !Ref LambdaPolicy
      Policies:
        - PolicyName: cloudwatch-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                - logs:CreateLogStream
                - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-lambda:*"
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda'
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Handler: index.custom_handler #filename.function_name
      Code:
        ZipFile: |
          def custom_handler(event,context):
            return true

  